spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wtu_app_server?serverTimezone=GMT%2B8&allowMultiQueries=true
      username: root
      password: abc123
server:
  servlet:
    session:
      timeout: 3600000
app:
  security:
    secret: "abcdefghijklmnopqrstuvwxyzABCDEFG"
    expire-minute: 1
