server:
  port: 7001

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wtu_app_server?serverTimezone=GMT%2B8
      username: root
      password: abc123

logging:
  level:
    pers.xds.wtuapp: debug

chat:
  ssl:
    certificate-path: "classpath:ssl/cert.crt"
    key-path: "classpath:ssl/pkcs8_private.key"
