server:
  port: 7001

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wtu_app_im?serverTimezone=GMT%2B8
      username: root
      password: abc123

logging:
  level:
    pers.xds.wtuapp: debug

im:
  ssl:
    certificate-path: "classpath:ssl/cert.crt"
    key-path: "classpath:ssl/pkcs8_private.key"
  idle:
    reader-idle-time-seconds: 10000000
app:
  security:
    secret: "abcdefghijklmnopqrstuvwxyzABCDEFG"
    expire-minute: 144000
