// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatResponseMessage.proto

package pers.xds.wtuapp.im.proto;

public final class ChatResponseMessageProto {
  private ChatResponseMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>int32 msgId = 1;</code>
     * @return The msgId.
     */
    int getMsgId();

    /**
     * <pre>
     * 谁发的
     * </pre>
     *
     * <code>int32 from = 2;</code>
     * @return The from.
     */
    int getFrom();

    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 创建时间, 秒级别时间戳
     * </pre>
     *
     * <code>int32 createTime = 4;</code>
     * @return The createTime.
     */
    int getCreateTime();

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>optional int32 type = 5;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>optional int32 type = 5;</code>
     * @return The type.
     */
    int getType();
  }
  /**
   * Protobuf type {@code ChatResponseMessage}
   */
  public static final class ChatResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatResponseMessage)
      ChatResponseMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatResponseMessage.newBuilder() to construct.
    private ChatResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatResponseMessage() {
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatResponseMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readInt32();
              break;
            }
            case 16: {

              from_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {

              createTime_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pers.xds.wtuapp.im.proto.ChatResponseMessageProto.internal_static_ChatResponseMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pers.xds.wtuapp.im.proto.ChatResponseMessageProto.internal_static_ChatResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.class, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int MSGID_FIELD_NUMBER = 1;
    private int msgId_;
    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>int32 msgId = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public int getMsgId() {
      return msgId_;
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private int from_;
    /**
     * <pre>
     * 谁发的
     * </pre>
     *
     * <code>int32 from = 2;</code>
     * @return The from.
     */
    @java.lang.Override
    public int getFrom() {
      return from_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 4;
    private int createTime_;
    /**
     * <pre>
     * 创建时间, 秒级别时间戳
     * </pre>
     *
     * <code>int32 createTime = 4;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public int getCreateTime() {
      return createTime_;
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>optional int32 type = 5;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>optional int32 type = 5;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0) {
        output.writeInt32(1, msgId_);
      }
      if (from_ != 0) {
        output.writeInt32(2, from_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (createTime_ != 0) {
        output.writeInt32(4, createTime_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(5, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgId_);
      }
      if (from_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, from_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (createTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, createTime_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage)) {
        return super.equals(obj);
      }
      pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage other = (pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (getFrom()
          != other.getFrom()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getCreateTime()
          != other.getCreateTime()) return false;
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (getType()
            != other.getType()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatResponseMessage)
        pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pers.xds.wtuapp.im.proto.ChatResponseMessageProto.internal_static_ChatResponseMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pers.xds.wtuapp.im.proto.ChatResponseMessageProto.internal_static_ChatResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.class, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.Builder.class);
      }

      // Construct using pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgId_ = 0;

        from_ = 0;

        content_ = "";

        createTime_ = 0;

        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pers.xds.wtuapp.im.proto.ChatResponseMessageProto.internal_static_ChatResponseMessage_descriptor;
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage getDefaultInstanceForType() {
        return pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.getDefaultInstance();
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage build() {
        pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage buildPartial() {
        pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage result = new pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.msgId_ = msgId_;
        result.from_ = from_;
        result.content_ = content_;
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage) {
          return mergeFrom((pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage other) {
        if (other == pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.getDefaultInstance()) return this;
        if (other.getMsgId() != 0) {
          setMsgId(other.getMsgId());
        }
        if (other.getFrom() != 0) {
          setFrom(other.getFrom());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getCreateTime() != 0) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgId_ ;
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>int32 msgId = 1;</code>
       * @return The msgId.
       */
      @java.lang.Override
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>int32 msgId = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(int value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>int32 msgId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = 0;
        onChanged();
        return this;
      }

      private int from_ ;
      /**
       * <pre>
       * 谁发的
       * </pre>
       *
       * <code>int32 from = 2;</code>
       * @return The from.
       */
      @java.lang.Override
      public int getFrom() {
        return from_;
      }
      /**
       * <pre>
       * 谁发的
       * </pre>
       *
       * <code>int32 from = 2;</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(int value) {
        
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 谁发的
       * </pre>
       *
       * <code>int32 from = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        
        from_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int createTime_ ;
      /**
       * <pre>
       * 创建时间, 秒级别时间戳
       * </pre>
       *
       * <code>int32 createTime = 4;</code>
       * @return The createTime.
       */
      @java.lang.Override
      public int getCreateTime() {
        return createTime_;
      }
      /**
       * <pre>
       * 创建时间, 秒级别时间戳
       * </pre>
       *
       * <code>int32 createTime = 4;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(int value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 创建时间, 秒级别时间戳
       * </pre>
       *
       * <code>int32 createTime = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>optional int32 type = 5;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>optional int32 type = 5;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>optional int32 type = 5;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>optional int32 type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:ChatResponseMessage)
    private static final pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage();
    }

    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<ChatResponseMessage>() {
      @java.lang.Override
      public ChatResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatResponseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatResponseMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChatResponseMessageGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatResponseMessageGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ChatResponseMessage messages = 1;</code>
     */
    java.util.List<pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage> 
        getMessagesList();
    /**
     * <code>repeated .ChatResponseMessage messages = 1;</code>
     */
    pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage getMessages(int index);
    /**
     * <code>repeated .ChatResponseMessage messages = 1;</code>
     */
    int getMessagesCount();
    /**
     * <code>repeated .ChatResponseMessage messages = 1;</code>
     */
    java.util.List<? extends pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageOrBuilder> 
        getMessagesOrBuilderList();
    /**
     * <code>repeated .ChatResponseMessage messages = 1;</code>
     */
    pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageOrBuilder getMessagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ChatResponseMessageGroup}
   */
  public static final class ChatResponseMessageGroup extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatResponseMessageGroup)
      ChatResponseMessageGroupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatResponseMessageGroup.newBuilder() to construct.
    private ChatResponseMessageGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatResponseMessageGroup() {
      messages_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatResponseMessageGroup();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatResponseMessageGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                messages_ = new java.util.ArrayList<pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              messages_.add(
                  input.readMessage(pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pers.xds.wtuapp.im.proto.ChatResponseMessageProto.internal_static_ChatResponseMessageGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pers.xds.wtuapp.im.proto.ChatResponseMessageProto.internal_static_ChatResponseMessageGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup.class, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup.Builder.class);
    }

    public static final int MESSAGES_FIELD_NUMBER = 1;
    private java.util.List<pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage> messages_;
    /**
     * <code>repeated .ChatResponseMessage messages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage> getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated .ChatResponseMessage messages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageOrBuilder> 
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <code>repeated .ChatResponseMessage messages = 1;</code>
     */
    @java.lang.Override
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated .ChatResponseMessage messages = 1;</code>
     */
    @java.lang.Override
    public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated .ChatResponseMessage messages = 1;</code>
     */
    @java.lang.Override
    public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(1, messages_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messages_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup)) {
        return super.equals(obj);
      }
      pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup other = (pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup) obj;

      if (!getMessagesList()
          .equals(other.getMessagesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMessagesCount() > 0) {
        hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getMessagesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatResponseMessageGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatResponseMessageGroup)
        pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pers.xds.wtuapp.im.proto.ChatResponseMessageProto.internal_static_ChatResponseMessageGroup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pers.xds.wtuapp.im.proto.ChatResponseMessageProto.internal_static_ChatResponseMessageGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup.class, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup.Builder.class);
      }

      // Construct using pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessagesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pers.xds.wtuapp.im.proto.ChatResponseMessageProto.internal_static_ChatResponseMessageGroup_descriptor;
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup getDefaultInstanceForType() {
        return pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup.getDefaultInstance();
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup build() {
        pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup buildPartial() {
        pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup result = new pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup(this);
        int from_bitField0_ = bitField0_;
        if (messagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            messages_ = java.util.Collections.unmodifiableList(messages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.messages_ = messages_;
        } else {
          result.messages_ = messagesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup) {
          return mergeFrom((pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup other) {
        if (other == pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup.getDefaultInstance()) return this;
        if (messagesBuilder_ == null) {
          if (!other.messages_.isEmpty()) {
            if (messages_.isEmpty()) {
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessagesIsMutable();
              messages_.addAll(other.messages_);
            }
            onChanged();
          }
        } else {
          if (!other.messages_.isEmpty()) {
            if (messagesBuilder_.isEmpty()) {
              messagesBuilder_.dispose();
              messagesBuilder_ = null;
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessagesFieldBuilder() : null;
            } else {
              messagesBuilder_.addAllMessages(other.messages_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage> messages_ =
        java.util.Collections.emptyList();
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          messages_ = new java.util.ArrayList<pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage>(messages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.Builder, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageOrBuilder> messagesBuilder_;

      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public java.util.List<pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage> getMessagesList() {
        if (messagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messages_);
        } else {
          return messagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public int getMessagesCount() {
        if (messagesBuilder_ == null) {
          return messages_.size();
        } else {
          return messagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage getMessages(int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);
        } else {
          return messagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public Builder setMessages(
          int index, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.set(index, value);
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public Builder setMessages(
          int index, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.set(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public Builder addMessages(pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public Builder addMessages(
          int index, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(index, value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public Builder addMessages(
          pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public Builder addMessages(
          int index, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage> values) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messages_);
          onChanged();
        } else {
          messagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public Builder clearMessages() {
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public Builder removeMessages(int index) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.remove(index);
          onChanged();
        } else {
          messagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.Builder getMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageOrBuilder getMessagesOrBuilder(
          int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);  } else {
          return messagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public java.util.List<? extends pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageOrBuilder> 
           getMessagesOrBuilderList() {
        if (messagesBuilder_ != null) {
          return messagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messages_);
        }
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.Builder addMessagesBuilder() {
        return getMessagesFieldBuilder().addBuilder(
            pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.Builder addMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().addBuilder(
            index, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .ChatResponseMessage messages = 1;</code>
       */
      public java.util.List<pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.Builder> 
           getMessagesBuilderList() {
        return getMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.Builder, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageOrBuilder> 
          getMessagesFieldBuilder() {
        if (messagesBuilder_ == null) {
          messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessage.Builder, pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageOrBuilder>(
                  messages_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          messages_ = null;
        }
        return messagesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatResponseMessageGroup)
    }

    // @@protoc_insertion_point(class_scope:ChatResponseMessageGroup)
    private static final pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup();
    }

    public static pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatResponseMessageGroup>
        PARSER = new com.google.protobuf.AbstractParser<ChatResponseMessageGroup>() {
      @java.lang.Override
      public ChatResponseMessageGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatResponseMessageGroup(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatResponseMessageGroup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatResponseMessageGroup> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pers.xds.wtuapp.im.proto.ChatResponseMessageProto.ChatResponseMessageGroup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatResponseMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatResponseMessageGroup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatResponseMessageGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ChatResponseMessage.proto\"s\n\023ChatRespo" +
      "nseMessage\022\r\n\005msgId\030\001 \001(\005\022\014\n\004from\030\002 \001(\005\022" +
      "\017\n\007content\030\003 \001(\t\022\022\n\ncreateTime\030\004 \001(\005\022\021\n\004" +
      "type\030\005 \001(\005H\000\210\001\001B\007\n\005_type\"B\n\030ChatResponse" +
      "MessageGroup\022&\n\010messages\030\001 \003(\0132\024.ChatRes" +
      "ponseMessageB6\n\030pers.xds.wtuapp.im.proto" +
      "B\030ChatResponseMessageProtoH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ChatResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatResponseMessage_descriptor,
        new java.lang.String[] { "MsgId", "From", "Content", "CreateTime", "Type", "Type", });
    internal_static_ChatResponseMessageGroup_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ChatResponseMessageGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatResponseMessageGroup_descriptor,
        new java.lang.String[] { "Messages", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
