// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgReceive.proto

package pers.xds.wtuapp.im.proto;

public final class MsgReceiveProto {
  private MsgReceiveProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageReceiveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageReceive)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 receivedId = 1;</code>
     * @return The receivedId.
     */
    int getReceivedId();
  }
  /**
   * Protobuf type {@code MessageReceive}
   */
  public static final class MessageReceive extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessageReceive)
      MessageReceiveOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageReceive.newBuilder() to construct.
    private MessageReceive(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageReceive() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageReceive();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageReceive(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              receivedId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pers.xds.wtuapp.im.proto.MsgReceiveProto.internal_static_MessageReceive_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pers.xds.wtuapp.im.proto.MsgReceiveProto.internal_static_MessageReceive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive.class, pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive.Builder.class);
    }

    public static final int RECEIVEDID_FIELD_NUMBER = 1;
    private int receivedId_;
    /**
     * <code>int32 receivedId = 1;</code>
     * @return The receivedId.
     */
    @java.lang.Override
    public int getReceivedId() {
      return receivedId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (receivedId_ != 0) {
        output.writeInt32(1, receivedId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (receivedId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, receivedId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive)) {
        return super.equals(obj);
      }
      pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive other = (pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive) obj;

      if (getReceivedId()
          != other.getReceivedId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RECEIVEDID_FIELD_NUMBER;
      hash = (53 * hash) + getReceivedId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageReceive}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageReceive)
        pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceiveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pers.xds.wtuapp.im.proto.MsgReceiveProto.internal_static_MessageReceive_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pers.xds.wtuapp.im.proto.MsgReceiveProto.internal_static_MessageReceive_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive.class, pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive.Builder.class);
      }

      // Construct using pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        receivedId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pers.xds.wtuapp.im.proto.MsgReceiveProto.internal_static_MessageReceive_descriptor;
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive getDefaultInstanceForType() {
        return pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive.getDefaultInstance();
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive build() {
        pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive buildPartial() {
        pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive result = new pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive(this);
        result.receivedId_ = receivedId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive) {
          return mergeFrom((pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive other) {
        if (other == pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive.getDefaultInstance()) return this;
        if (other.getReceivedId() != 0) {
          setReceivedId(other.getReceivedId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int receivedId_ ;
      /**
       * <code>int32 receivedId = 1;</code>
       * @return The receivedId.
       */
      @java.lang.Override
      public int getReceivedId() {
        return receivedId_;
      }
      /**
       * <code>int32 receivedId = 1;</code>
       * @param value The receivedId to set.
       * @return This builder for chaining.
       */
      public Builder setReceivedId(int value) {
        
        receivedId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 receivedId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceivedId() {
        
        receivedId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MessageReceive)
    }

    // @@protoc_insertion_point(class_scope:MessageReceive)
    private static final pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive();
    }

    public static pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageReceive>
        PARSER = new com.google.protobuf.AbstractParser<MessageReceive>() {
      @java.lang.Override
      public MessageReceive parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageReceive(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageReceive> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageReceive> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pers.xds.wtuapp.im.proto.MsgReceiveProto.MessageReceive getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageReceive_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageReceive_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MsgReceive.proto\"$\n\016MessageReceive\022\022\n\n" +
      "receivedId\030\001 \001(\005B-\n\030pers.xds.wtuapp.im.p" +
      "rotoB\017MsgReceiveProtoH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MessageReceive_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageReceive_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageReceive_descriptor,
        new java.lang.String[] { "ReceivedId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
