// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SyncRequestMessage.proto

package pers.xds.wtuapp.im.proto;

public final class SyncRequestMessageProto {
  private SyncRequestMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SyncRequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SyncRequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 是否用于拉取离线消息
     * </pre>
     *
     * <code>bool offline = 1;</code>
     * @return The offline.
     */
    boolean getOffline();

    /**
     * <code>int32 start = 2;</code>
     * @return The start.
     */
    int getStart();

    /**
     * <code>int32 end = 3;</code>
     * @return The end.
     */
    int getEnd();
  }
  /**
   * <pre>
   * 在线消息同步请求
   * </pre>
   *
   * Protobuf type {@code SyncRequestMessage}
   */
  public static final class SyncRequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SyncRequestMessage)
      SyncRequestMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SyncRequestMessage.newBuilder() to construct.
    private SyncRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SyncRequestMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SyncRequestMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SyncRequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              offline_ = input.readBool();
              break;
            }
            case 16: {

              start_ = input.readInt32();
              break;
            }
            case 24: {

              end_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pers.xds.wtuapp.im.proto.SyncRequestMessageProto.internal_static_SyncRequestMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pers.xds.wtuapp.im.proto.SyncRequestMessageProto.internal_static_SyncRequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage.class, pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage.Builder.class);
    }

    public static final int OFFLINE_FIELD_NUMBER = 1;
    private boolean offline_;
    /**
     * <pre>
     * 是否用于拉取离线消息
     * </pre>
     *
     * <code>bool offline = 1;</code>
     * @return The offline.
     */
    @java.lang.Override
    public boolean getOffline() {
      return offline_;
    }

    public static final int START_FIELD_NUMBER = 2;
    private int start_;
    /**
     * <code>int32 start = 2;</code>
     * @return The start.
     */
    @java.lang.Override
    public int getStart() {
      return start_;
    }

    public static final int END_FIELD_NUMBER = 3;
    private int end_;
    /**
     * <code>int32 end = 3;</code>
     * @return The end.
     */
    @java.lang.Override
    public int getEnd() {
      return end_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (offline_ != false) {
        output.writeBool(1, offline_);
      }
      if (start_ != 0) {
        output.writeInt32(2, start_);
      }
      if (end_ != 0) {
        output.writeInt32(3, end_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (offline_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, offline_);
      }
      if (start_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, start_);
      }
      if (end_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, end_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage)) {
        return super.equals(obj);
      }
      pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage other = (pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage) obj;

      if (getOffline()
          != other.getOffline()) return false;
      if (getStart()
          != other.getStart()) return false;
      if (getEnd()
          != other.getEnd()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OFFLINE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOffline());
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + getStart();
      hash = (37 * hash) + END_FIELD_NUMBER;
      hash = (53 * hash) + getEnd();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 在线消息同步请求
     * </pre>
     *
     * Protobuf type {@code SyncRequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SyncRequestMessage)
        pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pers.xds.wtuapp.im.proto.SyncRequestMessageProto.internal_static_SyncRequestMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pers.xds.wtuapp.im.proto.SyncRequestMessageProto.internal_static_SyncRequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage.class, pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage.Builder.class);
      }

      // Construct using pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        offline_ = false;

        start_ = 0;

        end_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pers.xds.wtuapp.im.proto.SyncRequestMessageProto.internal_static_SyncRequestMessage_descriptor;
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage getDefaultInstanceForType() {
        return pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage.getDefaultInstance();
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage build() {
        pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage buildPartial() {
        pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage result = new pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage(this);
        result.offline_ = offline_;
        result.start_ = start_;
        result.end_ = end_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage) {
          return mergeFrom((pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage other) {
        if (other == pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage.getDefaultInstance()) return this;
        if (other.getOffline() != false) {
          setOffline(other.getOffline());
        }
        if (other.getStart() != 0) {
          setStart(other.getStart());
        }
        if (other.getEnd() != 0) {
          setEnd(other.getEnd());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean offline_ ;
      /**
       * <pre>
       * 是否用于拉取离线消息
       * </pre>
       *
       * <code>bool offline = 1;</code>
       * @return The offline.
       */
      @java.lang.Override
      public boolean getOffline() {
        return offline_;
      }
      /**
       * <pre>
       * 是否用于拉取离线消息
       * </pre>
       *
       * <code>bool offline = 1;</code>
       * @param value The offline to set.
       * @return This builder for chaining.
       */
      public Builder setOffline(boolean value) {
        
        offline_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否用于拉取离线消息
       * </pre>
       *
       * <code>bool offline = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffline() {
        
        offline_ = false;
        onChanged();
        return this;
      }

      private int start_ ;
      /**
       * <code>int32 start = 2;</code>
       * @return The start.
       */
      @java.lang.Override
      public int getStart() {
        return start_;
      }
      /**
       * <code>int32 start = 2;</code>
       * @param value The start to set.
       * @return This builder for chaining.
       */
      public Builder setStart(int value) {
        
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 start = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStart() {
        
        start_ = 0;
        onChanged();
        return this;
      }

      private int end_ ;
      /**
       * <code>int32 end = 3;</code>
       * @return The end.
       */
      @java.lang.Override
      public int getEnd() {
        return end_;
      }
      /**
       * <code>int32 end = 3;</code>
       * @param value The end to set.
       * @return This builder for chaining.
       */
      public Builder setEnd(int value) {
        
        end_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 end = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnd() {
        
        end_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SyncRequestMessage)
    }

    // @@protoc_insertion_point(class_scope:SyncRequestMessage)
    private static final pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage();
    }

    public static pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyncRequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<SyncRequestMessage>() {
      @java.lang.Override
      public SyncRequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyncRequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SyncRequestMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SyncRequestMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pers.xds.wtuapp.im.proto.SyncRequestMessageProto.SyncRequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SyncRequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SyncRequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030SyncRequestMessage.proto\"A\n\022SyncReques" +
      "tMessage\022\017\n\007offline\030\001 \001(\010\022\r\n\005start\030\002 \001(\005" +
      "\022\013\n\003end\030\003 \001(\005B5\n\030pers.xds.wtuapp.im.prot" +
      "oB\027SyncRequestMessageProtoH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SyncRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SyncRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SyncRequestMessage_descriptor,
        new java.lang.String[] { "Offline", "Start", "End", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
