// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserMessage.proto

package pers.xds.wtuapp.im.proto;

public final class UserMessageProto {
  private UserMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 msgId = 1;</code>
     * @return The msgId.
     */
    int getMsgId();

    /**
     * <code>int32 to = 2;</code>
     * @return The to.
     */
    int getTo();

    /**
     * <code>int32 from = 3;</code>
     * @return The from.
     */
    int getFrom();

    /**
     * <code>string content = 4;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 4;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>int64 createTime = 5;</code>
     * @return The createTime.
     */
    long getCreateTime();
  }
  /**
   * Protobuf type {@code UserMessage}
   */
  public static final class UserMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserMessage)
      UserMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserMessage.newBuilder() to construct.
    private UserMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserMessage() {
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readInt32();
              break;
            }
            case 16: {

              to_ = input.readInt32();
              break;
            }
            case 24: {

              from_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 40: {

              createTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pers.xds.wtuapp.im.proto.UserMessageProto.internal_static_UserMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pers.xds.wtuapp.im.proto.UserMessageProto.internal_static_UserMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.class, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.Builder.class);
    }

    public static final int MSGID_FIELD_NUMBER = 1;
    private int msgId_;
    /**
     * <code>int32 msgId = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public int getMsgId() {
      return msgId_;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private int to_;
    /**
     * <code>int32 to = 2;</code>
     * @return The to.
     */
    @java.lang.Override
    public int getTo() {
      return to_;
    }

    public static final int FROM_FIELD_NUMBER = 3;
    private int from_;
    /**
     * <code>int32 from = 3;</code>
     * @return The from.
     */
    @java.lang.Override
    public int getFrom() {
      return from_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 4;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 4;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 5;
    private long createTime_;
    /**
     * <code>int64 createTime = 5;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public long getCreateTime() {
      return createTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0) {
        output.writeInt32(1, msgId_);
      }
      if (to_ != 0) {
        output.writeInt32(2, to_);
      }
      if (from_ != 0) {
        output.writeInt32(3, from_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(5, createTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgId_);
      }
      if (to_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, to_);
      }
      if (from_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, from_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, createTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage)) {
        return super.equals(obj);
      }
      pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage other = (pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (getTo()
          != other.getTo()) return false;
      if (getFrom()
          != other.getFrom()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getCreateTime()
          != other.getCreateTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserMessage)
        pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pers.xds.wtuapp.im.proto.UserMessageProto.internal_static_UserMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pers.xds.wtuapp.im.proto.UserMessageProto.internal_static_UserMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.class, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.Builder.class);
      }

      // Construct using pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgId_ = 0;

        to_ = 0;

        from_ = 0;

        content_ = "";

        createTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pers.xds.wtuapp.im.proto.UserMessageProto.internal_static_UserMessage_descriptor;
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage getDefaultInstanceForType() {
        return pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.getDefaultInstance();
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage build() {
        pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage buildPartial() {
        pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage result = new pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage(this);
        result.msgId_ = msgId_;
        result.to_ = to_;
        result.from_ = from_;
        result.content_ = content_;
        result.createTime_ = createTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage) {
          return mergeFrom((pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage other) {
        if (other == pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.getDefaultInstance()) return this;
        if (other.getMsgId() != 0) {
          setMsgId(other.getMsgId());
        }
        if (other.getTo() != 0) {
          setTo(other.getTo());
        }
        if (other.getFrom() != 0) {
          setFrom(other.getFrom());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgId_ ;
      /**
       * <code>int32 msgId = 1;</code>
       * @return The msgId.
       */
      @java.lang.Override
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>int32 msgId = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(int value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 msgId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = 0;
        onChanged();
        return this;
      }

      private int to_ ;
      /**
       * <code>int32 to = 2;</code>
       * @return The to.
       */
      @java.lang.Override
      public int getTo() {
        return to_;
      }
      /**
       * <code>int32 to = 2;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(int value) {
        
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 to = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        
        to_ = 0;
        onChanged();
        return this;
      }

      private int from_ ;
      /**
       * <code>int32 from = 3;</code>
       * @return The from.
       */
      @java.lang.Override
      public int getFrom() {
        return from_;
      }
      /**
       * <code>int32 from = 3;</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(int value) {
        
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 from = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        
        from_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 4;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>int64 createTime = 5;</code>
       * @return The createTime.
       */
      @java.lang.Override
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>int64 createTime = 5;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 createTime = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserMessage)
    }

    // @@protoc_insertion_point(class_scope:UserMessage)
    private static final pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage();
    }

    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserMessage>
        PARSER = new com.google.protobuf.AbstractParser<UserMessage>() {
      @java.lang.Override
      public UserMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserMessageGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserMessageGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .UserMessage message = 1;</code>
     */
    java.util.List<pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage> 
        getMessageList();
    /**
     * <code>repeated .UserMessage message = 1;</code>
     */
    pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage getMessage(int index);
    /**
     * <code>repeated .UserMessage message = 1;</code>
     */
    int getMessageCount();
    /**
     * <code>repeated .UserMessage message = 1;</code>
     */
    java.util.List<? extends pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageOrBuilder> 
        getMessageOrBuilderList();
    /**
     * <code>repeated .UserMessage message = 1;</code>
     */
    pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageOrBuilder getMessageOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code UserMessageGroup}
   */
  public static final class UserMessageGroup extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserMessageGroup)
      UserMessageGroupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserMessageGroup.newBuilder() to construct.
    private UserMessageGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserMessageGroup() {
      message_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserMessageGroup();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserMessageGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                message_ = new java.util.ArrayList<pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              message_.add(
                  input.readMessage(pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          message_ = java.util.Collections.unmodifiableList(message_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pers.xds.wtuapp.im.proto.UserMessageProto.internal_static_UserMessageGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pers.xds.wtuapp.im.proto.UserMessageProto.internal_static_UserMessageGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup.class, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.util.List<pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage> message_;
    /**
     * <code>repeated .UserMessage message = 1;</code>
     */
    @java.lang.Override
    public java.util.List<pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage> getMessageList() {
      return message_;
    }
    /**
     * <code>repeated .UserMessage message = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageOrBuilder> 
        getMessageOrBuilderList() {
      return message_;
    }
    /**
     * <code>repeated .UserMessage message = 1;</code>
     */
    @java.lang.Override
    public int getMessageCount() {
      return message_.size();
    }
    /**
     * <code>repeated .UserMessage message = 1;</code>
     */
    @java.lang.Override
    public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage getMessage(int index) {
      return message_.get(index);
    }
    /**
     * <code>repeated .UserMessage message = 1;</code>
     */
    @java.lang.Override
    public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageOrBuilder getMessageOrBuilder(
        int index) {
      return message_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < message_.size(); i++) {
        output.writeMessage(1, message_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < message_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, message_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup)) {
        return super.equals(obj);
      }
      pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup other = (pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup) obj;

      if (!getMessageList()
          .equals(other.getMessageList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMessageCount() > 0) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserMessageGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserMessageGroup)
        pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pers.xds.wtuapp.im.proto.UserMessageProto.internal_static_UserMessageGroup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pers.xds.wtuapp.im.proto.UserMessageProto.internal_static_UserMessageGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup.class, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup.Builder.class);
      }

      // Construct using pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messageBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pers.xds.wtuapp.im.proto.UserMessageProto.internal_static_UserMessageGroup_descriptor;
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup getDefaultInstanceForType() {
        return pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup.getDefaultInstance();
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup build() {
        pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup buildPartial() {
        pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup result = new pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup(this);
        int from_bitField0_ = bitField0_;
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            message_ = java.util.Collections.unmodifiableList(message_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup) {
          return mergeFrom((pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup other) {
        if (other == pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup.getDefaultInstance()) return this;
        if (messageBuilder_ == null) {
          if (!other.message_.isEmpty()) {
            if (message_.isEmpty()) {
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessageIsMutable();
              message_.addAll(other.message_);
            }
            onChanged();
          }
        } else {
          if (!other.message_.isEmpty()) {
            if (messageBuilder_.isEmpty()) {
              messageBuilder_.dispose();
              messageBuilder_ = null;
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessageFieldBuilder() : null;
            } else {
              messageBuilder_.addAllMessages(other.message_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage> message_ =
        java.util.Collections.emptyList();
      private void ensureMessageIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          message_ = new java.util.ArrayList<pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage>(message_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.Builder, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageOrBuilder> messageBuilder_;

      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public java.util.List<pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage> getMessageList() {
        if (messageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(message_);
        } else {
          return messageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public int getMessageCount() {
        if (messageBuilder_ == null) {
          return message_.size();
        } else {
          return messageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage getMessage(int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);
        } else {
          return messageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public Builder setMessage(
          int index, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.set(index, value);
          onChanged();
        } else {
          messageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public Builder setMessage(
          int index, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public Builder addMessage(pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(value);
          onChanged();
        } else {
          messageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public Builder addMessage(
          int index, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(index, value);
          onChanged();
        } else {
          messageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public Builder addMessage(
          pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public Builder addMessage(
          int index, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public Builder addAllMessage(
          java.lang.Iterable<? extends pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage> values) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, message_);
          onChanged();
        } else {
          messageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public Builder removeMessage(int index) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.remove(index);
          onChanged();
        } else {
          messageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.Builder getMessageBuilder(
          int index) {
        return getMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageOrBuilder getMessageOrBuilder(
          int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);  } else {
          return messageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public java.util.List<? extends pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageOrBuilder> 
           getMessageOrBuilderList() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(message_);
        }
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.Builder addMessageBuilder() {
        return getMessageFieldBuilder().addBuilder(
            pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.Builder addMessageBuilder(
          int index) {
        return getMessageFieldBuilder().addBuilder(
            index, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .UserMessage message = 1;</code>
       */
      public java.util.List<pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.Builder> 
           getMessageBuilderList() {
        return getMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.Builder, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessage.Builder, pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageOrBuilder>(
                  message_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserMessageGroup)
    }

    // @@protoc_insertion_point(class_scope:UserMessageGroup)
    private static final pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup();
    }

    public static pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserMessageGroup>
        PARSER = new com.google.protobuf.AbstractParser<UserMessageGroup>() {
      @java.lang.Override
      public UserMessageGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserMessageGroup(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserMessageGroup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserMessageGroup> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pers.xds.wtuapp.im.proto.UserMessageProto.UserMessageGroup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserMessageGroup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserMessageGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UserMessage.proto\"[\n\013UserMessage\022\r\n\005ms" +
      "gId\030\001 \001(\005\022\n\n\002to\030\002 \001(\005\022\014\n\004from\030\003 \001(\005\022\017\n\007c" +
      "ontent\030\004 \001(\t\022\022\n\ncreateTime\030\005 \001(\003\"1\n\020User" +
      "MessageGroup\022\035\n\007message\030\001 \003(\0132\014.UserMess" +
      "ageB.\n\030pers.xds.wtuapp.im.protoB\020UserMes" +
      "sageProtoH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserMessage_descriptor,
        new java.lang.String[] { "MsgId", "To", "From", "Content", "CreateTime", });
    internal_static_UserMessageGroup_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserMessageGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserMessageGroup_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
